version: '3.8'

services:
  # Lightweight Document Agent - Standalone (connects to existing services)
  doc-agent:
    build:
      context: .
      dockerfile: Dockerfile.lightweight-agent
    container_name: lightweight-doc-agent
    environment:
      - AGENT_ID=doc-agent-001
      - MAX_MEMORY_MB=512
      - MAX_CPU_PERCENT=50
      - BATCH_SIZE=10
      - MAX_CONCURRENT_TASKS=2
      - WEAVIATE_HOST=host.docker.internal
      - WEAVIATE_HTTP_PORT=8090
      - KNOWLEDGE_BASE_URL=http://host.docker.internal:8001
      - REDIS_URL=redis://host.docker.internal:6379
      - LOG_LEVEL=INFO
    ports:
      - "8010:8010"
    volumes:
      - ./data:/app/data:ro  # Read-only access
      - ./logs:/app/logs
      - ./src:/app/src:ro  # Read-only access to existing grading system
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8010/health')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
