version: '3.8'

services:
  # Redis service
  redis:
    image: redis:7-alpine
    container_name: ai-chat-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-chat-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-chat-backend
    ports:
      - "8002:8002"
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=1
    networks:
      - ai-chat-network
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./knowledge_base:/app/knowledge_base:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-chat-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_API_URL=http://localhost:8002
      - BACKEND_API_URL=http://localhost:8002
    networks:
      - ai-chat-network
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  ai-chat-network:
    driver: bridge
