version: '3.8'

# ============================================================================
# NeuroForge Local Development Environment - Simplified for Local Usage
# Optimized for development, testing, and local experimentation
# ============================================================================

services:
  # ============================================================================
  # BACKEND API - Development Focused
  # ============================================================================
  neuroforge-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: neuroforge/api:dev
    container_name: neuroforge-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - REDIS_URL=redis://neuroforge-redis:6379
      - DATABASE_URL=postgresql://neuroforge:dev_password@neuroforge-postgres:5432/neuroforge
      - WEAVIATE_URL=http://neuroforge-weaviate:8080
    volumes:
      - ./src:/app/src
      - ./knowledge_base:/app/knowledge_base
      - ./configs:/app/configs
      - ./logs:/app/logs
    networks:
      - neuroforge-local
    restart: unless-stopped
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # ============================================================================
  # FRONTEND - Development with Hot Reload
  # ============================================================================
  neuroforge-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: neuroforge/frontend:dev
    container_name: neuroforge-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXT_PUBLIC_TTS_ENABLED=false
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - neuroforge-local
    restart: unless-stopped
    command: npm run dev
    depends_on:
      neuroforge-api:
        condition: service_healthy

  # ============================================================================
  # DATABASES - Local Development Setup
  # ============================================================================
  neuroforge-postgres:
    image: postgres:15-alpine
    container_name: neuroforge-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=neuroforge
      - POSTGRES_USER=neuroforge
      - POSTGRES_PASSWORD=dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - neuroforge-local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neuroforge -d neuroforge"]
      interval: 10s
      timeout: 5s
      retries: 5

  neuroforge-redis:
    image: redis:7-alpine
    container_name: neuroforge-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - neuroforge-local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  neuroforge-weaviate:
    image: semitechnologies/weaviate:1.24.0
    container_name: neuroforge-weaviate
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - neuroforge-local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/meta"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ============================================================================
  # OPTIONAL SERVICES - Enable with --profile
  # ============================================================================
  neuroforge-prometheus:
    image: prom/prometheus:latest
    container_name: neuroforge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - neuroforge-local
    profiles:
      - monitoring

  neuroforge-grafana:
    image: grafana/grafana:latest
    container_name: neuroforge-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=dev_password
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - neuroforge-local
    profiles:
      - monitoring

  # ============================================================================
  # DEVELOPMENT TOOLS
  # ============================================================================
  neuroforge-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: neuroforge-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@neuroforge.dev
      - PGADMIN_DEFAULT_PASSWORD=dev_password
    networks:
      - neuroforge-local
    profiles:
      - dev-tools

  neuroforge-redis-insight:
    image: redis/redisinsight:latest
    container_name: neuroforge-redis-insight
    ports:
      - "5540:5540"
    networks:
      - neuroforge-local
    profiles:
      - dev-tools

# ============================================================================
# NETWORKS & VOLUMES - Local Development
# ============================================================================
networks:
  neuroforge-local:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  weaviate_data:
  prometheus_data:
  grafana_data:
